module.exports = {
    User: require('./user'),
    Role: require('./role'),
    Movie: require('./movie'),
    Cinema: require('./cinema'),
    Screen: require('./screen'),
    Seat: require('./seat'),
    Showtime: require('./showtime'),
    SeatHold: require('./seatHold'),
    Snack: require('./snack'),
    Order: require('./order'),
    LoginAttempt: require('./loginAttempt'),
    Notification: require('./notification'),
    Favourite: require('./favourite'),
    Review: require('./review'),
    Contact: require('./contact'),
    GiftCard: require('./giftCard'),
    Staff: require('./staff'),
    Shift: require('./shift'),
    ScreenConfiguration: require('./screenConfiguration'),
    Equipment: require('./equipment'),
    MaintenanceLog: require('./maintenanceLog'),
    MoviePerformance: require('./moviePerformance'),
    CustomerAnalytics: require('./customerAnalytics'),
};